export const LinkMap: Record<string, {name: string, link: string}> = {
  'abyss': {name: 'ABySS', link: 'https://github.com/bcgsc/abyss'},
  'AlignGraph': {name: 'AlignGraph', link: 'https://github.com/baoe/AlignGraph'},
  'anaconda3': {name: 'Anaconda 3', link: 'https://docs.anaconda.com/anaconda/packages/old-pkg-lists/5.3.0/py3.6_win-64/'},
  'bamtools': {name: 'Bamtools', link: 'https://github.com/pezmaster31/bamtools'},
  'biopython': {name: 'Biopython', link: 'https://github.com/biopython/biopython'},
  'blast': {name: 'BLAST', link: 'https://blast.ncbi.nlm.nih.gov/Blast.cgi?CMD=Web&PAGE_TYPE=BlastHome'},
  'boost': {name: 'Boost', link: 'https://www.boost.org/'},
  'bowtie2': {name: 'Bowtie 2', link: 'https://github.com/BenLangmead/bowtie2'},
  'bwa': {name: 'BWA', link: 'https://github.com/lh3/bwa'},
  'cap3': {name: 'CAP3', link: 'http://seq.cs.iastate.edu/cap3.html'},
  'CAP-miRSeq': {name: 'CAP-miRSeq', link: 'http://bioinformaticstools.mayo.edu/downloads/cap-mirna/CAP-miRSeq_UserGuide.pdf'},
  'CD-HIT': {name: 'CD-HIT', link: 'https://github.com/weizhongli/cdhit'},
  'cgmaptools': {name: 'CGmapTools', link: 'https://github.com/guoweilong/cgmaptools'},
  'clust': {name: 'Clust', link: 'https://github.com/BaselAbujamous/clust'},
  'cmake': {name: 'CMake', link: 'https://cmake.org/'},
  'cufflinks': {name: 'Cufflinks', link: 'https://github.com/cole-trapnell-lab/cufflinks'},
  'diamond': {name: 'DIAMOND', link: 'http://www.diamondsearch.org/index.php'},
  'django-celery': {name: 'Celery', link: 'hhttps://docs.celeryproject.org/en/stable/django/index.html'},
  'FAST': {name: 'FAST', link: 'https://www.frontiersin.org/articles/10.3389/fgene.2015.00172/full'},
  'FastQC': {name: 'FastQC', link: 'http://www.bioinformatics.babraham.ac.uk/projects/fastqc/'},
  'fastqc': {name: 'FastQC', link: 'http://www.bioinformatics.babraham.ac.uk/projects/fastqc/'},
  'gcc': {name: 'GCC', link: 'https://gcc.gnu.org/'},
  'glimmer': {name: 'Glimmer', link: 'http://www.cbcb.umd.edu/software/glimmer/glimmer2.jun01.shtml'},
  'hisat2': {name: 'HI-SAT2', link: 'http://daehwankimlab.github.io/hisat2/'},
  'hmmer': {name: 'HMMER', link: 'http://hmmer.org/'},
  'htop': {name: 'htop', link: 'https://hisham.hm/htop/'},
  'IGVTools': {name: 'IGVTools', link: 'https://software.broadinstitute.org/software/igv/igvtools'},
  'Jellyfish': {name: 'jellyfish', link: 'https://github.com/gmarcais/Jellyfish'},
  'Kent': {name: 'kent', link: 'https://github.com/ucscGenomeBrowser/kent'},
  'maker': {name: 'MAKER', link: 'https://www.yandell-lab.org/software/maker.html'},
  'matlab': {name: 'MATLAB', link: 'https://www.mathworks.com/products/matlab.html'},
  'matplotlib': {name: 'Matplotlib', link: 'https://matplotlib.org/'},
  'mpich': {name: 'MPICH', link: 'https://www.mpich.org/'},
  'mvapich': {name: 'MVAPICH', link: 'http://bioinfocore.usu.edu/'},
  'openmpi': {name: 'OpenMPI', link: 'http://bioinfocore.usu.edu/'},
  'pantherScore': {name: 'PANTHER Score', link: 'https://bio.tools/pantherscore'},
  'parallel': {name: 'GNU Parallel', link: 'https://www.gnu.org/software/parallel/'},
  'php': {name: 'PHP', link: 'https://www.php.net/'},
  'picard': {name: 'Picard', link: 'https://broadinstitute.github.io/picard/'},
  'python2': {name: 'Python 2', link: 'https://www.python.org/doc/sunset-python-2/'},
  'python3': {name: 'Python 3', link: 'https://www.python.org/'},
  'qiime': {name: 'QIIME', link: 'http://qiime.org/'},
  'quast': {name: 'QUAST', link: 'http://bioinf.spbau.ru/quast'},
  'R': {name: 'R', link: 'https://www.r-project.org/'},
  'repeatmasker': {name: 'RepeatMasker', link: 'http://www.repeatmasker.org/'},
  'rstudio': {name: 'RStudio', link: 'https://rstudio.com/'},
  'salmon': {name: 'Salmon', link: 'https://github.com/COMBINE-lab/salmon'},
  'SOAPsuite': {name: 'SOAP Suite', link: 'http://www.htslib.org/'},
  'SPAdes': {name: 'SPAdes', link: 'http://cab.spbu.ru/software/spades/'},
  'sparsehash': {name: 'SparseHash', link: 'https://github.com/sparsehash/sparsehash'},
  'star': {name: 'STAR', link: 'https://github.com/alexdobin/STAR'},
  'tmux': {name: 'tmux', link: 'https://github.com/tmux/tmux'},
  'tophat': {name: 'TopHat', link: 'http://ccb.jhu.edu/software/tophat/manual.shtml'},
  'trim_galore': {name: 'Trim Galore', link: 'https://www.bioinformatics.babraham.ac.uk/projects/trim_galore/'},
  'Trinity': {name: 'Trinity Desktop Environment', link: 'https://www.trinitydesktop.org/'},
  'vim': {name: 'vim', link: 'https://www.vim.org/'}
}
